name: Deploy King Panel ğŸš€

on:
  push:
    branches:
      - main  # Se activa cuando subes cambios a la rama 'main'

permissions:
  contents: write # Permiso para publicar en el repositorio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node.js ğŸ”§
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          cache: 'npm'

      - name: Install Dependencies ğŸ“¦
        run: npm ci

      - name: Build Angular App ğŸ—ï¸
        # Se usa /king/ porque ese es el nombre de tu repositorio segÃºn los logs
        run: npx ng build --configuration production --base-href /king/

      - name: Deploy ğŸš€  
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Ajustado a 'dist/king' que es donde tus logs indican que se genera el build
          folder: dist/king
          branch: gh-pages